drivers: staging: prima: sme_Trace: add missing function prototype
>>>
../drivers/staging/prima/CORE/SME/src/sme_common/sme_Trace.c:285:33: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
  285 | void sme_register_debug_callback()
      |                                 ^
      |                                  void
<<<

Signed-off-by: chickendrop89 <chickendrop89@gmail.com>