drivers: staging: prima: limTrace: add missing function prototype
>>>
../drivers/staging/prima/CORE/MAC/src/pe/lim/limTrace.c:347:33: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
  347 | void lim_register_debug_callback()
      |                                 ^
      |                                  void
<<<

Signed-off-by: chickendrop89 <chickendrop89@gmail.com>